tinyMCE.init({
	entity_encoding : "raw",
	mode : "textareas",
	theme : "advanced",
	plugins : "safari,advhr,advimage,advlink,inlinepopups,media,searchreplace,visualchars,nonbreaking,xhtmlxtras",
	theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2 : "copy,cut,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor",
	theme_advanced_buttons3 : "hr,removeformat,visualaid,|,sub,sup,|,charmap,media,advhr",
	theme_advanced_buttons4 : "cite,abbr,acronym,del,ins,attribs,|,visualchars,blockquote",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,
	force_p_newlines : false,
	force_br_newlines : true,
	convert_newlines_to_brs : true,
	remove_linebreaks : true,
	forced_root_block : '',
	relative_urls : false
});